# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: odenrep.com
  secret_key_base: 8baf26dc5ad51abc965e0ec3d37ff8bfab40b5142b10129e1c518007e2a32e5830c76057dce9ef4db593a0a6d42c431004a5dc719c973c3ab2fa0269a3d0cfd7
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
  linked_app_id: <%= ENV["LINKED_APP_ID"] %>
  linked_app_secret: <%= ENV["LINKED_APP_SECRET"] %>
  sendgrid_key: <%= ENV["SENDGRID_KEY"] %>
test:
  domain_name: example.com
  secret_key_base: 43fba24911159cbe9e4ee95458000b0a21698f9c5719d4d54bc56466083275d7b74018e2c93ddb6d112aaca4d78081d444a8e1861d3dfad07610cd636d596e38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: odenrep.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_app_secret: <%= ENV["FB_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
  sendgrid_key: <%= ENV["SENDGRID_KEY"] %>
  linked_app_id: <%= ENV["LINKED_APP_ID"] %>
  linked_app_secret: <%= ENV["LINKED_APP_SECRET"] %>
